-- Create crm_types table
CREATE TABLE IF NOT EXISTS public.crm_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  description text NULL,
  default_url text NULL,
  request_format text NOT NULL DEFAULT 'json',
  auth_type text NOT NULL DEFAULT 'none',
  auth_header_name text NULL,
  autologin_url_path text NULL,
  lead_id_path text NULL,
  field_mappings jsonb NOT NULL DEFAULT '{}',
  required_fields jsonb NOT NULL DEFAULT '[]',
  field_labels jsonb NOT NULL DEFAULT '{}',
  field_descriptions jsonb NOT NULL DEFAULT '{}',
  extra_body_fields jsonb NOT NULL DEFAULT '{}',
  extra_headers jsonb NOT NULL DEFAULT '{}',
  success_check jsonb NULL,
  error_check jsonb NULL,
  ai_analysis jsonb NULL,
  original_docs text NULL,
  use_forwarder boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_types_pkey PRIMARY KEY (id),
  CONSTRAINT crm_types_code_key UNIQUE (code)
);
